
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon May 27 07:13:12 BST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INPUT = 24;
  public static final int AND = 18;
  public static final int MULTIPLY = 4;
  public static final int ELSE = 21;
  public static final int PLUS = 3;
  public static final int GTHANEQ = 13;
  public static final int NOTEQ = 14;
  public static final int OR = 26;
  public static final int RPAREN = 8;
  public static final int THEN = 28;
  public static final int WHILE = 30;
  public static final int SEMI = 15;
  public static final int NOT = 25;
  public static final int END = 22;
  public static final int IDEN = 31;
  public static final int TRUE = 16;
  public static final int IF = 23;
  public static final int LPAREN = 7;
  public static final int DO = 20;
  public static final int BEGIN = 19;
  public static final int NUMBER = 32;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int GTHAN = 11;
  public static final int FALSE = 17;
  public static final int LTHAN = 10;
  public static final int MINUS = 2;
  public static final int error = 1;
  public static final int EQ = 6;
  public static final int LTHANEQ = 12;
  public static final int EQEQ = 9;
  public static final int OUTPUT = 27;
  public static final int VAR = 29;
}

