top.location!=document.location&&(top.location.href=document.location.href);var IE_URL_MAX_LENGTH=2E3;"undefined"===typeof IS_MOBILE&&(IS_MOBILE=!1);var splitDomain=document.domain.split(".");1<splitDomain.length&&(document.domain=splitDomain[splitDomain.length-2]+"."+splitDomain[splitDomain.length-1]);
var aurrp=Cookie.read("aurrp"),aurrp=null===aurrp?!0:"1"===aurrp,shouldUseLikes=Cookie.read("uselikes"),shouldUseLikes=null===shouldUseLikes?!0:"1"===shouldUseLikes,shouldUseFbLikes,contentTop,logoElt,likeButtonElement=null,COMETBackend=new Class({Implements:[Options,Events],initialize:function(b){this.setOptions(b);this.clientID=null;this.stopped=!1},connect:function(b,a,c,d,k,g,j){var l=this;l.server=b;l.stratusNearID=a;l.askedQuestion=c;l.wantsSpy=d;l.canSaveQuestion=k;l.fbAccessToken=g;l.topics=
j;subdomainManager.subdomainWindow(b,function(a){l.reqWindow=a;l.gotReqWindow()})},resume:function(b,a){var c=this;c.server=b;c.clientID=a;subdomainManager.subdomainWindow(b,function(a){c.reqWindow=a;c.getEvents()})},gotReqWindow:function(){var b=this,a=subdomainManager.fixUrl(b.server,"/start?rcs=1&firstevents=1&spid="+(b.stratusNearID||"")+(IS_MOBILE?"&m=1":""));"string"===typeof b.askedQuestion&&(a+="&ask="+encodeURIComponent(b.askedQuestion));"string"===typeof b.fbAccessToken&&(a+="&fbaccesstoken="+
encodeURIComponent(b.fbAccessToken));b.wantsSpy&&(a+="&wantsspy=1");b.canSaveQuestion&&(a+="&cansavequestion=1");b.topics&&b.topics.length&&(a+="&topics="+encodeURIComponent(JSON.encode(b.topics)));killHeaders(new b.reqWindow.Request.JSON({url:a,onSuccess:function(a){b.clientID=a.clientID?a.clientID:a;b.fireEvent("connectedToServer");a.events&&b.gotEvents(a.events);b.getEvents()},onFailure:function(){b.fireEvent("failedToConnect")}})).post()},getEvents:function(b){void 0===b&&(b=0);if(!this.stopped){2<
b&&(this.fireEvent("connectionDied","Lost contact with server, and couldn't reach it after 3 tries."),this.stopped=!0);var a=this;killHeaders(new a.reqWindow.Request.JSON({url:subdomainManager.fixUrl(a.server,"/events"),onSuccess:function(b){a.stopped||(null===b?(a.stopped=!0,a.fireEvent("connectionDied","Server was unreachable for too long and your connection was lost.")):(a.gotEvents(b),a.getEvents()))},onFailure:function(){setTimeout(function(){a.getEvents(b+1)},2500)}})).post({id:this.clientID})}},
gotEvents:function(b){var a=this;$each(b,function(b){switch(b[0]){case "waiting":a.fireEvent("waiting");break;case "connected":a.fireEvent("strangerConnected",b[1]);break;case "gotMessage":a.fireEvent("gotMessage",b[1]);break;case "strangerDisconnected":a.stopped=!0;a.fireEvent("strangerDisconnected");break;case "typing":a.fireEvent("typing");break;case "stoppedTyping":a.fireEvent("stoppedTyping");break;case "recaptchaRequired":a.fireEvent("recaptchaRequired",b[1]);break;case "recaptchaRejected":a.fireEvent("recaptchaRejected",
b[1]);break;case "count":onlineCountUpdated(b[1]);break;case "spyMessage":a.fireEvent("spyMessage",[b[1],b[2]]);break;case "spyTyping":a.fireEvent("spyTyping",b[1]);break;case "spyStoppedTyping":a.fireEvent("spyStoppedTyping",b[1]);break;case "spyDisconnected":a.stopped=!0;a.fireEvent("spyDisconnected",b[1]);break;case "question":a.fireEvent("question",b[1]);break;case "error":a.stopped=!0;a.fireEvent("error",b[1]);break;case "commonLikes":a.fireEvent("commonLikes",[b[1]]);break;case "antinudeBanned":a.stopped=
!0,a.fireEvent("antinudeBanned",[b[1]])}})},sendMessage:function(b){killHeaders(new this.reqWindow.Request({url:subdomainManager.fixUrl(this.server,"/send"),data:{msg:b,id:this.clientID}})).send()},typing:function(){killHeaders(new this.reqWindow.Request({url:subdomainManager.fixUrl(this.server,"/typing"),data:{id:this.clientID}})).send()},stopTyping:function(){killHeaders(new this.reqWindow.Request({url:subdomainManager.fixUrl(this.server,"/stoppedtyping"),data:{id:this.clientID}})).send()},submitRecaptcha:function(b,
a){killHeaders(new this.reqWindow.Request({url:subdomainManager.fixUrl(this.server,"/recaptcha"),data:{id:this.clientID,challenge:b,response:a}})).send()},disconnect:function(){killHeaders(new this.reqWindow.Request({url:subdomainManager.fixUrl(this.server,"/disconnect"),data:{id:this.clientID}})).send();this.stopped=!0},stopLookingForCommonLikes:function(){killHeaders(new this.reqWindow.Request({url:subdomainManager.fixUrl(this.server,"/stoplookingforcommonlikes"),data:{id:this.clientID}})).send()}}),
flashCb_socketConnected,flashCb_socketGotPacket,flashCb_socketClosed,flashCb_socketError;function resetFlashSocketCallbacks(){flashCb_socketConnected=function(){};flashCb_socketGotPacket=function(){};flashCb_socketClosed=function(){};flashCb_socketError=function(){}}function parseQueryString(b){for(var a={},b=b.split("&"),c=0;c<b.length;c++){var d=b[c].split("="),k=decodeURIComponent(d[0].replace(/\+/g," ")),d=decodeURIComponent(d[1].replace(/\+/g," "));a[k]=d}return a}
function middotify(b){for(var a=new Element("span"),c=0;c<b.length;c++)0<c&&a.appendText(" \u2022\u00a0"),a.grab(b[c]);return a}
var FlashSocketBackend=new Class({Implements:[Options,Events],initialize:function(b){this.setOptions(b);this.stopped=!1;flashCb_socketConnected=this.socketConnected.bind(this);flashCb_socketGotPacket=this.socketGotPacket.bind(this);flashCb_socketClosed=this.socketClosedPreConnect.bind(this);flashCb_socketError=this.socketErrorPreConnect.bind(this)},connect:function(b,a,c,d,k,g,j){this.stratusNearID=a||"";this.askedQuestion=c;this.wantsSpy=d||!1;this.canSaveQuestion=k||!1;this.fbAccessToken=g;this.topics=
j;$("flash").socketConnect(b,1365);var l=this;this.checkFlashIsAliveInterval=setInterval(function(){if(!$("flash")||!$("flash").socketConnect)l.fireEvent("connectionDied","Flash plugin crashed."),l.done()},1E3)},socketClosedPreConnect:function(){resetFlashSocketCallbacks();this.fireEvent("failedToConnect")},socketErrorPreConnect:function(){resetFlashSocketCallbacks();this.fireEvent("failedToConnect")},socketConnected:function(){flashCb_socketClosed=this.socketClosedPostConnect.bind(this);flashCb_socketError=
this.socketErrorPostConnect.bind(this);var b={caps:"recaptcha",spid:this.stratusNearID};"string"===typeof this.askedQuestion&&(b.ask=this.askedQuestion);"string"===typeof this.fbAccessToken&&(b.fbaccesstoken=this.fbAccessToken);this.wantsSpy&&(b.wantsspy="1");this.canSaveQuestion&&(b.cansavequestion="1");this.topics&&this.topics.length&&(b.topics=JSON.encode(this.topics));var a=Cookie.read("abtest");null!==a&&(b.abtest=a);$("flash").socketSendPacket("omegleStart","web-flash?"+Hash.toQueryString(b));
this.fireEvent("connectedToServer")},socketGotPacket:function(b,a){a=decodeURIComponent(a);switch(b){case "w":this.fireEvent("waiting");break;case "c":setFlashSocketsWorkCookie();this.fireEvent("strangerConnected",a);break;case "m":this.fireEvent("gotMessage",a);break;case "d":this.done();this.fireEvent("strangerDisconnected");break;case "t":this.fireEvent("typing");break;case "st":this.fireEvent("stoppedTyping");break;case "recaptchaRequired":a=parseQueryString(a);this.fireEvent("recaptchaRequired",
a.publicKey);break;case "recaptchaRejected":a=parseQueryString(a);this.fireEvent("recaptchaRejected",[a.publicKey,a.errorCode]);break;case "count":onlineCountUpdated(parseInt(a,10));break;case "spyMessage":a=parseQueryString(a);this.fireEvent("spyMessage",[a.n,a.m]);break;case "spyTyping":this.fireEvent("spyTyping",a);break;case "spyStoppedTyping":this.fireEvent("spyStoppedTyping",a);break;case "spyDisconnected":this.done();this.fireEvent("spyDisconnected",a);break;case "question":this.fireEvent("question",
a);break;case "error":this.done();this.fireEvent("error",a);break;case "commonLikes":this.fireEvent("commonLikes",[JSON.decode(a)]);break;case "client_id":this.clientID=a;break;case "antinudeBanned":this.done(),this.fireEvent("antinudeBanned",[a])}},socketClosedPostConnect:function(){this.fireEvent("connectionDied","Lost connection with server.");this.done()},socketErrorPostConnect:function(b){b?"."!=b[b.length-1]&&(b+="."):b="internal error.";this.fireEvent("connectionDied",b);this.done()},sendMessage:function(b){$("flash").socketSendPacket("s",
b)},typing:function(){$("flash").socketSendPacket("t","")},stopTyping:function(){$("flash").socketSendPacket("st","")},disconnect:function(){$("flash").socketSendPacket("d","");this.done()},submitRecaptcha:function(b,a){$("flash").socketSendPacket("recaptcha",Hash.toQueryString({challenge:b,response:a}))},stopLookingForCommonLikes:function(){$("flash").socketSendPacket("stoplookingforcommonlikes","")},done:function(){this.stopped=!0;$("flash")&&$("flash").socketClose&&$("flash").socketClose();resetFlashSocketCallbacks();
this.checkFlashIsAliveInterval&&(clearInterval(this.checkFlashIsAliveInterval),this.checkFlashIsAliveInterval=null)}}),flashSocketsWillWork="yes"===Cookie.read("flashsocketswork"),flashSocketsWork=!1;function setFlashSocketsWorkCookie(){Cookie.write("flashsocketswork","yes",{duration:1/12})}function flashCb_socketsWork(){flashSocketsWork=!0;setFlashSocketsWorkCookie()}
var MetaBackend=new Class({Implements:[Options,Events],initialize:function(b){this.setOptions(b);self.numResumes=0;self.stopped=!1},plugInBackend:function(){var b=this;$each("connectedToServer failedToConnect waiting strangerConnected gotMessage strangerDisconnected typing stoppedTyping recaptchaRequired recaptchaRejected spyMessage spyTyping spyStoppedTyping spyDisconnected question error commonLikes antinudeBanned".split(" "),function(a){b.backend.addEvent(a,function(){b.stopped=b.backend.stopped;
b.fireEvent(a,arguments)})});b.backend.addEvent("connectionDied",function(){serverManager.unsetKnownGood();if(b.backend.clientID&&1>numResumes&&!b.stopped){numResumes++;var a=b.backend.clientID;b.backend=new COMETBackend;b.plugInBackend();b.backend.resume(serverManager.pickServer(),a)}else b.stopped=!0,b.fireEvent("connectionDied",arguments)})},connect:function(){this.backend=flashSocketsWork&&$("flash")&&$("flash").socketConnect?new FlashSocketBackend:new COMETBackend;this.plugInBackend();for(var b=
[serverManager.pickServer()],a=0;a<arguments.length;a++)b.push(arguments[a]);this.backend.connect.apply(this.backend,b)},sendMessage:function(b){this.backend.sendMessage(b)},typing:function(){this.backend.typing()},stopTyping:function(){this.backend.stopTyping()},disconnect:function(){this.stopped=!0;this.backend.disconnect()},submitRecaptcha:function(b,a){this.backend.submitRecaptcha(b,a)},stopLookingForCommonLikes:function(){this.backend.stopLookingForCommonLikes()}}),savedIntro=null,savedHeader=
null;function startFirstChat(){IS_MOBILE?(logoElt=$("logo"),savedHeader=$("header"),$("header").dispose(),contentTop=0):contentTop=$("intro").offsetTop;savedIntro=$("intro");$("intro").dispose();startNewChat.apply(null,arguments)}
function mobileHouseAd(){var b=null,a=null;navigator.userAgent.match(/iPod|iPhone|iPad/)&&(b="/static/iosappad.png",a="http://click.linksynergy.com/fs-bin/stat?id=Ih/d3nAE7gg&offerid=146261&type=3&subid=0&tmpid=1826&RD_PARM1=http%253A%252F%252Fitunes.apple.com%252Fus%252Fapp%252Fomegle%252Fid318233700%253Fmt%253D8%2526uo%253D6%2526partnerId%253D30");return b&&a?(a=new Element("a",{href:a}),b=new Element("img",{src:b,width:300,height:50,border:0}),a.grab(b),a):null}
function showIntro(){IS_MOBILE&&(savedHeader&&logoElt)&&(savedHeader.grab(logoElt,"top"),$(document.body).grab(savedHeader));savedIntro&&$(document.body).grab(savedIntro);IS_MOBILE&&setTimeout(function(){scrollTo(0,1)},100);mobileAdWrapper&&$("mobileadwrapper2")&&mobileAdWrapper.setStyles({display:"block",top:$("mobileadwrapper2").getPosition().y+"px"});var b=makeTopicSettings();$("topicsettingscontainer")&&($("topicsettingscontainer").empty(),$("topicsettingscontainer").grab(b))}
function commify(b){var a="",c;do{c=(b%1E3).toString();for(b=Math.floor(b/1E3);0!=b&&3>c.length;)c="0"+c;a=c+a;b&&(a=","+a)}while(0!=b);return a}var statusTimeout=null;function scheduleStatusUpdate(){null!==statusTimeout&&clearTimeout(statusTimeout);statusTimeout=setTimeout(updateStatus,6E4)}function onlineCountUpdated(b){var a=$("onlinecount");if(a&&!(void 0===b||null===b||isNaN(b)))a.set("html","<strong>"+commify(b)+"</strong> strangers online"),$("onlinecount")&&scheduleStatusUpdate()}
function randomSpyMode(){return 0.25>Math.random()?"spy":"spyee"}var idealSpyMode=randomSpyMode(),firstStatusUpdate=!0,antinudeServers=[],lastScreenshotTime=null,screenshotPercent=0;
function updateStatus(){onlineCountTimeout=null;var b=serverManager.pickServer();subdomainManager.subdomainWindow(b,function(){killHeaders(new Request.JSON({url:subdomainManager.fixUrl(b,"/status"),onSuccess:function(a){onlineCountUpdated(a.count);idealSpyMode=2>a.spyQueueTime&&2>a.spyeeQueueTime?randomSpyMode():a.spyQueueTime>a.spyeeQueueTime?"spyee":"spy";a.timestamp&&timeManager.gotAccurateTime(new Date(1E3*a.timestamp));a.servers&&a.servers.length&&serverManager.setServerList(a.servers);antinudeServers=
a.antinudeservers||[];screenshotPercent=a.antinudepercent||0;firstStatusUpdate=!1},onFailure:function(){serverManager.unsetKnownGood();setTimeout(updateStatus,500)}})).get()})}function setShouldUseLikes(b){shouldUseLikes=b;Cookie.write("uselikes",b?"1":"0",{duration:365,domain:document.domain})}
function makeShouldUseLikesCheckbox(){var b=new Element("label"),a=new Element("input",{type:"checkbox",checked:shouldUseLikes});a.addEvent("change",function(){setShouldUseLikes(a.checked)});b.grab(a);b.appendText(" Find strangers with common interests");return b}var initOfFbCallbacks=[],initOfFbComplete=!1;
window.fbAsyncInit=function(){FB.init({appId:"372387627273",cookie:!0,status:!0,xfbml:!0,oauth:!0,channelUrl:"http://"+document.domain+"/static/channel.html"});initOfFbComplete=!0;for(var b=0;b<initOfFbCallbacks.length;b++)initOfFbCallbacks[b]();initOfFbCallbacks=null};
function onReady(){function b(){$("tryspymodetext").empty();var a=makeSpyOptionsForm(startFirstChat);a.form.setStyle("marginTop","0.5em");a.form.setStyle("marginBottom","0.5em");$("tryspymodetext").appendText("Spy mode lets you ask a question and watch two strangers discuss it. (The strangers volunteer to be watched.)");$("tryspymodetext").grab(new Element("br"));$("tryspymodetext").appendText("Ask anything you like, but try to keep questions open-ended and thought-provoking.");$("tryspymodetext").grab(a.form);
var b=new Element("div"),c=new Element("button",{text:"Ask strangers"});c.addEvent("click",a.go);b.grab(c);$("tryspymodetext").grab(b);b=new Element("div");b.setStyle("font-size","0.9em");b.set("text","Or you can try ");c=new Element("a");c.set("text","discussing questions");c.set("href","javascript:");c.addEvent("click",function(b){b.preventDefault();startFirstChat(!1,null,!0,!1)});b.grab(c);b.appendText(" instead.");$("tryspymodetext").grab(b);a.focus()}updateStatus();if(null===$("textbtn")&&null===
$("chatbtn"))window.addEvent("load",onReady);else{"undefined"!==typeof FastClick&&new FastClick(document.body);($("textbtn")||$("chatbtn")).addEvent("click",function(){startFirstChat(!1)});if($("feedback")){var a=$$("#feedback h2");"#feedback"==location.hash?($("feedback").addClass("expanded"),$("feedbackmessage").focus()):$("feedback").addClass("collapsed");a.addEvent("needsclick");a.addEvent("click",function(){$("feedback").hasClass("expanded")?($("feedback").removeClass("expanded"),$("feedback").addClass("collapsed")):
($("feedback").removeClass("collapsed"),$("feedback").addClass("expanded"),$("feedbackmessage").focus())})}$("mobileadwrapper")&&(mobileAdWrapper=$("mobileadwrapper"),mobileAdWrapperSize=mobileAdWrapper.getSize(),"body"!==mobileAdWrapper.getParent().get("tag")&&($(document.body).grab(mobileAdWrapper),mobileAdWrapper.setStyle("display","none")),$("mobileadwrapper2")&&($("mobileadwrapper2").setStyles({width:mobileAdWrapperSize.x+"px",height:mobileAdWrapperSize.y+"px",margin:"auto","text-align":"center"}),
a=$("mobileadwrapper2").getPosition(),mobileAdWrapper.setStyles({display:"block",position:"absolute",top:a.y+"px",left:a.x+"px"})));$("flashwrapper")&&($("flashwrapper").addEvent("mouseleave",function(){$("flash").mouseOut&&$("flash").mouseOut()}),$("flashwrapper").addEvent("mouseenter",function(){$("flash").mouseOver&&$("flash").mouseOver()}),swfobject.embedSWF("/static/omegle.swf?14","flash",320,520,"10.0.0",null,null,null,null,function(b){b.success||$("videobtnstatus").set("html",'Requires <a href="http://get.adobe.com/flashplayer/">Flash 10</a>.')}));
$("tryspymode")&&($("tryspymode").addClass("needsclick"),$("tryspymode").addEvent("click",function g(){$("tryspymode").removeEvent("click",g);$("tryspymode").removeClass("collapsed");if("spy"==idealSpyMode)b();else{$("tryspymodetext").empty();$("tryspymodetext").set("html","Spy mode gives you and a stranger a <strong>random question</strong> to discuss. The question is submitted by a third stranger who can watch the conversation, but can't join in.");var a=new Element("button",{text:"Check it out!"});
a.addEvent("click",function(a){a.preventDefault();startFirstChat(!1,null,!0,!1)});$("tryspymodetext").grab(new Element("br"));$("tryspymodetext").grab(a);a=new Element("div");a.setStyle("font-size","0.9em");a.set("text","Or you can try ");var c=new Element("a");c.set("text","asking a question");c.set("href","javascript:");c.addEvent("click",function(a){a.preventDefault();b()});a.grab(c);a.appendText(" instead.");$("tryspymodetext").grab(a)}}));a=makeTopicSettings();$("topicsettingscontainer")&&$("topicsettingscontainer").grab(a);
if(!IS_MOBILE&&/OS X 10.[78]/.test(navigator.userAgent)){a=new Element("div");a.setStyles({margin:"0.5em 0","text-align":"center"});var c=new Element("span");c.setStyles({background:"#555",color:"white",padding:"0.25em","border-radius":"0.25em","-moz-border-radius":"0.25em","-webkit-border-radius":"0.25em"});c.appendText("Trouble enabling your webcam? It's an Adobe Flash bug. ");var d=new Element("a",{href:"http://www.youtube.com/watch?v=0tyHV_cz5gA",target:"_blank"});d.setStyles({color:"#AAAAFF"});
d.appendText("This video explains how to make it work.");c.grab(d);a.grab(c);$("chattypes").grab(a,"before")}}}window.addEvent("domready",onReady);function onLoad(){IS_MOBILE&&setTimeout(function(){window.scrollTo(0,1)},0)}window.addEvent("load",onLoad);
var topicManager=function(){function b(){Cookie.write("topiclist",JSON.encode(c),{duration:365,domain:document.domain})}function a(a){return a.toLowerCase().replace(/[^a-zA-Z0-9]/g,"")}var c=[],d=Cookie.read("topiclist");d&&(c=JSON.decode(d));b();return{list:function(){return c},add:function(d){var g=a(d);if(!g)return!1;for(var j=0;j<c.length;j++)if(a(c[j])===g)return!1;c.push(d);b();return!0},remove:function(d){for(var d=a(d),g=0;g<c.length;g++)if(a(c[g])===d)return c.splice(g,1),b(),!0;return!1},
normalize:a}}();
function makeTopicSettings(){function b(a){var b=new Element("span",{"class":"topictag"}),c=new Element("span",{"class":"topictagtext",text:a});b.grab(c);c=new Element("span",{"class":"topictagdelete",html:"&times;"});c.addEvent("click",function(){b.destroy();topicManager.remove(a);d()});b.grab(c);l.grab(b);c=new Element("span");c.setStyle("font-size",0);c.appendText(" ");l.grab(c)}function a(){d();setTimeout(d,0)}function c(){var a=r.get("value");r.set("value","");for(var a=a.split(","),a=a.map(function(a){return a.trim()}),
c=0;c<a.length;c++){var g=a[c];topicManager.add(g)&&(b(g),setShouldUseLikes(!0),N.set("checked",!0))}d()}function d(){r.value||topicManager.list().length?v.setStyle("display","none"):v.setStyle("display","inline");q.checked||topicManager.list().length?y.setStyle("display","block"):y.setStyle("display","none")}function k(a){Cookie.write("fblikes",a?"1":"0",{duration:365,domain:document.domain})}function g(){z.setStyle("display","block");shouldUseFbLikes&&(q.set("checked",!0),d());"0"!==Cookie.read("fblikes")&&
FB.getLoginStatus(function(a){a.authResponse?(q.set("checked",!0),k(!0),shouldUseFbLikes=!0):k(!1);d()})}var j=new Element("div",{"class":"topictageditor"}),l=new Element("span",{"class":"topictagwrapper"});j.grab(l);$each(topicManager.list(),b);var v=new Element("span",{"class":"topicplaceholder"});v.appendText("What are you into?");j.grab(v);var r=new Element("input",{type:"text","class":"newtopicinput"});r.addEvent("keydown",a);r.addEvent("keypress",a);r.addEvent("keyup",a);r.addEvent("keydown",
function(a){32===a.code&&!r.get("value")&&a.preventDefault();if(13===a.code||188===a.code)a.preventDefault(),c()});r.addEvent("blur",c);j.grab(r);j.addClass("needsclick");j.addEvent("click",function(){r.focus()});var n=new Element("div");n.grab(j);var z=new Element("div");z.setStyle("display","none");var j=new Element("label"),q=new Element("input",{type:"checkbox"});q.addEvent("click",function(a){q.checked?(a.preventDefault(),FB.login(function(a){a.authResponse&&(shouldUseFbLikes=!0,k(!0),q.set("checked",
!0),setShouldUseLikes(!0),N.set("checked",!0),d())},{scope:"user_likes"})):(shouldUseFbLikes=!1,k(!1));setTimeout(d,0)});j.grab(q);j.appendText(" Use my Facebook likes");z.grab(j);n.grab(z);var y=new Element("div"),j=makeShouldUseLikesCheckbox(),N=j.getElement("input");y.grab(j);n.grab(y);d();initOfFbComplete?g():initOfFbCallbacks.push(g);return n}
var subdomainManager=function(){var b={},a={};return{subdomainWindow:function(c,d){if(void 0!==Browser.Request().withCredentials)d(window);else if(b[c])d(b[c]);else{a[c]?a[c].push(d):a[c]=[d];var k=new Element("iframe",{src:"http://"+c+"/static/xhrframe.html",width:0,height:0,frameBorder:0});k.setStyle("display","none");$(document.body).grab(k)}},fixUrl:function(a,b){return void 0!==Browser.Request().withCredentials?"http://"+a+b:b},iframeLoaded:function(c,d){if(!b[c]&&(b[c]=d,a[c])){for(var k=0;k<
a[c].length;k++)(0,a[c][k])(d);delete a[c]}}}}(),serverManager=function(){var b=[],a=null,c=null,d={setKnownGood:function(){a=c},unsetKnownGood:function(){a=null},pickServer:function(){if(null!==a&&-1!==b.indexOf(a))return a;var d=b.shift();b.push(d);return c=d},setServerList:function(a){var c,d,l;for(c=1;c<a.length;c++)d=Math.floor(Math.random()*(1+c)),d!=c&&(l=a[c],a[c]=a[d],a[d]=l);for(c=0;c<a.length;c++)d=a[c],-1===b.indexOf(d)&&b.unshift(d);for(c=0;c<b.length;c++)d=b[c],-1===a.indexOf(d)&&b.splice(c,
1)}};d.setServerList("front1.omegle.com front2.omegle.com front3.omegle.com front4.omegle.com front5.omegle.com front6.omegle.com front7.omegle.com".split(" "));return d}(),timeManager=function(){var b=0;return{now:function(){var a=new Date;a.setTime(a.getTime()+b);return a},gotAccurateTime:function(a){b=a-new Date}}}(),flashCb_gotNearID,flashCb_errorConnectingToStratus,flashCb_camAvailable;
function resetStratusCallbacks(){flashCb_gotNearID=function(){};flashCb_errorConnectingToStratus=function(){}}function resetCameraCallbacks(){flashCb_camAvailable=function(){}}function resetFlashCallbacks(){resetStratusCallbacks();resetCameraCallbacks()}resetFlashCallbacks();var videoChatEnabled=!1;
function flashCb_init(b){-1===navigator.userAgent.indexOf("AppleWebKit")&&$("flashwrapper").addClass("inited");b?(videoChatEnabled=!0,$("videobtn").set("src",$("videobtn").get("src").replace("-disabled","-enabled")),$("videobtn").removeClass("disabled"),$("videobtn").addEvent("click",function(){startFirstChat(!0)}),$("videobtnstatus").set("html","&nbsp;")):$("videobtnstatus").set("html",'Requires a webcam.<br><a target="_blank" href="http://www.amazon.com/mn/search/?_encoding=UTF8&node=172511&tag=omegle-20&linkCode=ur2&camp=1789&brr=1&rd=1&creative=390957">Shop for a webcam here.</a>');
flashSocketsWillWork&&$("flash")&&$("flash").socketConnect?flashSocketsWork=!0:$("flash")&&$("flash").testSockets&&$("flash").testSockets(serverManager.pickServer(),1365)}function killHeaders(b){delete b.headers["X-Requested-With"];delete b.headers["X-Request"];return b}
function makeSpyOptionsForm(b,a,c){function d(){b(!1,l.value,!1,v.checked)}void 0===a&&(a="");void 0===c&&(c=!0);var k=new Element("form");k.addEvent("submit",function(a){a.preventDefault();d()});var g=new Element("div"),j=new Element("label");j.grab(new Element("strong",{text:"Enter a question:"}));j.grab(new Element("br"));var l=new Element("input",{"class":"questionInput",value:a,maxlength:200});j.grab(l);g.grab(j);k.grab(g);a=new Element("div");a.setStyle("marginTop","0.5em");var g=new Element("label"),
v=new Element("input",{type:"checkbox",checked:c});g.grab(v);g.appendText(" I want Omegle to reuse this question if it's good enough.");a.grab(g);k.grab(a);return{form:k,focus:function(){l.focus()},go:d}}var flashingInterval=null;function isFlashing(){return null!==flashingInterval}
function startFlashing(){function b(){var b=a.pop();document.title=b[0];setFavicon(b[1]);a.unshift(b)}if(!IS_MOBILE&&!isFlashing()){var a=[["___Omegle___","/static/favicon.png"],["\u00af\u00af\u00afOmegle\u00af\u00af\u00af","/static/altfavicon.png"]];flashingInterval=setInterval(b,500);b();$(document).addEvent("mousemove",mouseMove);$(document).addEvent("keydown",stopFlashing);$(document).addEvent("focus",stopFlashing);$(window).addEvent("mousemove",mouseMove);$(window).addEvent("keydown",stopFlashing);
$(window).addEvent("focus",stopFlashing)}}var lastCoords=null;function mouseMove(b){b=b.page;null!==lastCoords&&(b.x!=lastCoords.x||b.y!=lastCoords.y)&&stopFlashing();lastCoords=b}
function stopFlashing(){isFlashing()&&(clearInterval(flashingInterval),flashingInterval=null,document.title="Omegle",setFavicon("/static/favicon.png"),$(document).removeEvent("mousemove",mouseMove),$(document).removeEvent("keydown",stopFlashing),$(document).removeEvent("focus",stopFlashing),$(window).removeEvent("mousemove",mouseMove),$(window).removeEvent("keydown",stopFlashing),$(window).removeEvent("focus",stopFlashing))}
function setFavicon(b){for(var a=$$("link"),c=0;c<a.length;c++)if("icon"===a[c].rel){a[c].href=b;return}b=new Element("link",{rel:"icon",type:"image/png",href:b});$$("head")[0].grab(b)}var mobileAdWrapper=null,mobileADWrapperSize=null,currentAffiliate=null;
function startNewChat(b,a,c,d){function k(){var a=document.activeElement;if(!a)return m.get("disabled");a=a.nodeName.toLowerCase();return"input"!==a&&"textarea"!==a}function g(a){27===a.code&&a.preventDefault();!IS_MOBILE&&!m.get("disabled")&&(8===a.code||37==a.code||39==a.code||46<=a.code&&90>=a.code||96<=a.code&&111>=a.code)?m.focus():8===a.code&&k()&&a.preventDefault()}function j(a){27===a.code&&(a.preventDefault(),pa());8===a.code&&k()&&a.preventDefault()}function l(){scrollElt.scrollTop=scrollElt.scrollHeight}
function v(a,b){var c=new Element("form");c.setStyle("display","none");c.set("target","_blank");c.set("action","http://logs.omegle.com/generate");c.set(b);var a=a||{host:1},d={log:JSON.encode(O)};G&&(d.topics=JSON.encode(G));d=$extend(d,a);$each(d,function(a,b){var e=new Element("input",{type:"hidden",name:b,value:a});c.grab(e)});$(document.body).grab(c);c.submit();setTimeout(function(){c.dispose()},0)}function r(a,b){var c=new Element("div",{"class":"logitem"});c.grab(a);var d;d=IS_MOBILE?!0:scrollElt.scrollTop>=
scrollElt.scrollHeight-scrollElt.clientHeight;0===H.length||b?U.grab(c):c.inject(H[0].element,"before");d&&(IS_MOBILE?setTimeout(l,10):l());return c}function n(a,b,c,d){(void 0===b||b)&&startFlashing();var f;void 0===d||d&&"string"!==typeof d?(b=!0,f=null):"string"===typeof d?(b=!0,f=d):b=!1;"string"===typeof a?(d=new Element("p",{"class":"statuslog"}),d.appendText(a),null===f&&(f=a)):(d=new Element("div",{"class":"statuslog"}),d.grab(a));b&&(!fa&&null!==f)&&O.push([f]);return r(d,c)}function z(a){"undefined"!==
typeof Recaptcha&&Recaptcha.destroy();null!==D&&D.dispose();D=r(a);initialLogIsRecaptcha=!1}function q(a,b){"undefined"!==typeof Recaptcha&&Recaptcha.destroy();null!==D&&D.dispose();D=n(a,!1,!1,"undefined"===typeof b?!1:b);initialLogIsRecaptcha=!1}function y(a,b,c){var d=new Element("p",{"class":b}),b=new Element("strong",{"class":"msgsource"});b.appendText(a+":");d.grab(b);d.appendText(" ");var f=!0;$each(c.split("\n"),function(a){f||d.grab(new Element("br"));f=!1;d.appendText(a)});r(d);fa||O.push([a+
":",c])}function N(a,b){if("you"==a){var c="youmsg",d="You";ga=!0}else c="strangermsg",d="Stranger",startFlashing(),qa=!0;b=b.trim();"stranger"===a&&-1!==b.toLowerCase().indexOf("videobam")||(y(d,c,b),"stranger"===a&&(-1!==b.indexOf("FBI")||-1!==b.toLowerCase().indexOf("federal bureau"))&&n("If the above message says you have been reported to the FBI, it is not legitimate. Please ignore it."),"stranger"===a&&(-1!==b.toLowerCase().indexOf("facebook.com/profile.php?")&&-1===b.toLowerCase().indexOf("id="))&&
n("THE STRANGER DOES NOT KNOW YOUR FACEBOOK INFO. The above link directs anyone to their own profile; it is not really a link to your profile specifically."))}function M(a){for(var b=0;b<H.length;b++)if(!a||H[b].name===a){H[b].element.dispose();H.splice(b,1);break}}function ma(){M("Stranger")}function na(a){M(a);var b=n(a+" is typing...",!1,!0,!1);H.push({name:a,element:b})}function oa(){$("logo").removeEvent("click",ra);null!==C&&(clearInterval(C),C=null);P&&$(window).removeEvent("resize",P);IS_MOBILE||
($(document).removeEvent("keydown",g),$(document).removeEvent("keyup",j));V.dispose()}function E(e,B,h,g){if(void 0===e){if(null!==Q){Q.go();return}e=b}e&&(B=null,g=h=!1);void 0===B&&(B=a);void 0===h&&(h=c);void 0===g&&(g=d);null!==F&&(clearTimeout(F),F=null);e||sa();oa();startNewChat(e,B,h,g)}function ra(){if(!stopped){if(!confirm("Are you sure you want to end your chat?"))return;W()}$("logo").setStyle("cursor","default");oa();showIntro()}function sa(){null!==F&&(clearTimeout(F),F=null);$("flash")&&
$("flash").turnOffCamera&&$("flash").turnOffCamera()}function x(){resetFlashCallbacks();M();fa=!0;initialLogIsRecaptcha&&("undefined"!==typeof Recaptcha&&Recaptcha.destroy(),D.dispose(),D=null,initialLogIsRecaptcha=!1);A&&(A.destroy(),A=null);for(var e=0;e<ta.length;e++)ta[e].dispose();mots=[];b&&($("flash").stopChat&&$("flash").stopChat(),F=setTimeout(function(){F=null;sa()},3E4));X&&clearTimeout(X);!b&&!IS_MOBILE&&(Y.setStyle("margin-right",0),R.setStyle("margin-right",0),(new Fx.Tween(Y,{duration:"short"})).start("margin-right",
0,"176px"),(new Fx.Tween(R,{duration:"short"})).start("margin-right",0,"176px"),$("adwrapper2").setStyle("margin-left","160px"),(new Fx.Tween($("adwrapper2"),{duration:"short"})).start("margin-left","160px",0),setTimeout(l,300));$(document.body).removeClass("inconversation");$(document.body).removeClass("videochat");m.set("disabled",!0);m.addClass("disabled");J.set("disabled",!0);m.blur();J.blur();K("new");window.onbeforeunload=null;$(window).removeEvent("unload",W);stopped=!0;U.get("html");var B=
null;if(document.createRange&&(window.getSelection||document.getSelection))B=document.createRange(),B.selectNodeContents(U);Z&&(Q=makeSpyOptionsForm(E,a,d),r(Q.form),IS_MOBILE||Q.focus());var e=new Element("div"),h=new Element("input");h.type="submit";h.value="Start a new conversation";h.addEvent("click",function(){E()});e.grab(h);h=new Element("a");h.set("text","switch to "+(b||c||a?"text":"video"));h.set("href","#");h.addEvent("click",function(e){e.preventDefault();c||a?E(!1,null,!1,!1):E(!b)});
if(c||a||videoChatEnabled)e.appendText(" or "),e.grab(h);if((c||a)&&videoChatEnabled)h=new Element("a"),h.set("text","video"),h.set("href","#"),h.addEvent("click",function(a){a.preventDefault();E(!0)}),e.appendText(" or "),e.grab(h);n(e,!1,!1);if(!c&&!a){var g=new Element("div"),e=makeShouldUseLikesCheckbox();!shouldUseFbLikes&&!topicManager.list().length&&(e.getElement("input").set("checked",!1),e.getElement("input").set("disabled",!0));g.grab(e);e=new Element("a",{href:"javascript:",text:"(Settings)"});
e.addEvent("click",function(a){a.preventDefault();null!==L&&L();g.empty();a=makeTopicSettings();g.grab(a);a.getElement("input").focus()});g.appendText(" ");g.grab(e);r(g)}e=new Element("div",{"class":"logsavelinks"});h=new Element("span",{"class":"conversationgreat"});h.set("text","Was this chat great?");h.addEvent("click",function(){v()});e.grab(h);var h=[],f=JSON.encode(O);encodeURIComponent(f);f=new Element("a");f.set("text","Get a link");f.set("href","javascript:");f.addEvent("click",function(a){a.preventDefault();
v()});h.push(f);null!==B&&!IS_MOBILE&&(f=new Element("a",{href:"javascript:",text:"Select all"}),f.addEvent("click",function(a){a.preventDefault();a=window.getSelection?window.getSelection():document.getSelection();a.removeAllRanges();a.addRange(B)}),h.push(f));var f=[],p=new Element("a",{href:"javascript:",text:"Facebook"});p.addEvent("click",function(a){a.preventDefault();v({facebook:1})});f.push(p);p=new Element("a",{href:"javascript:",text:"Tumblr"});p.addEvent("click",function(a){a.preventDefault();
v({tumblr:1})});f.push(p);p=new Element("a",{href:"javascript:",text:"Twitter"});p.addEvent("click",function(a){a.preventDefault();var a=screen.height,b=Math.round(screen.width/2-275),c=0;420<a&&(c=Math.round(a/2-210));window.open("","intent","scrollbars=yes,resizable=yes,toolbar=no,location=yes,width=550,height=420,left="+b+",top="+c);v({tweet:1},{target:"intent"})});f.push(p);p=new Element("a",{href:"javascript:",text:"reddit"});p.addEvent("click",function(a){a.preventDefault();v({reddit:1})});
f.push(p);e.appendText(" Save the log: ");e.grab(middotify(h));e.appendText(" \u2022\u00a0Or post log to: ");e.grab(middotify(f));h=aurrp;if(Z||ga&&qa)n(e,!1,!1);else if(b){var j=function(){if(k)q||(q=!0,x.set("text","Not automatically rerolling."),t.dispose(),s.grab(u),K("new"));else{var a="Automatically rerolling in: "+i+" second";1!=i&&(a+="s");x.set("text",a);K("new",i)}},i=3,k=!h,q=!1,s=new Element("div"),x=new Element("span");s.grab(x);s.appendText(" ");var t=new Element("input");t.set("type",
"button");t.set("value","Stop");L=function(){null!==C&&(clearInterval(C),C=null,k=!0,j())};t.addEvent("click",function(){L()});s.grab(t);var u=new Element("label");u.setStyle("color","black");u.setStyle("font-weight","normal");var w=new Element("input");w.set("type","checkbox");w.set("checked",h);w.addEvent("change",function(){var a=w.checked;aurrp=a;Cookie.write("aurrp",a?"1":"0",{duration:365,domain:document.domain})});u.grab(w);u.appendText(" Auto-reroll next time");j();n(s,!1,!1);k||(C=setInterval(function(){i--;
1>i?(clearInterval(C),C=null,E()):j()},1E3))}c&&!ga&&n("Please try to discuss the question, not just disconnect!");if(null!==currentAffiliate){e=currentAffiliate;if(e.tests){h=100*Math.random();f=!1;for(p=0;p<e.tests.length;p++){test=e.tests[p];if(h<test.percentage){f=!0;break}h-=test.percentage}f&&(e=Hash.combine(test,e))}f=b?"video":"text";e.trackCode&&(f=e.trackCode);e.baseTrackCode&&(f=e.baseTrackCode+"-"+f);var y,h=new Element("span"),f=e.url.replace(/\$/g,f),f=new Element("a",{href:f,target:"_blank"});
f.setStyles({"text-decoration":"none"});e.image&&(p=new Element("img",{src:e.image,alt:""}),p.setStyles({border:"0 none","vertical-align":"middle"}),f.grab(p),f.appendText(" "));e.text&&(p=new Element("span"),p.setStyles({color:"#000000","text-decoration":"none","font-weight":"normal",background:"#FF0000",padding:"0.25em 0.5em","border-radius":"0.5em","-moz-border-radius":"0.5em","-webkit-border-radius":" 0.5em"}),e.style&&p.setStyles(e.style),p.set("text",e.text),f.grab(p));h.grab(f);e=new Element("span");
e.set("html","&times;");e.setStyles({cursor:"default",color:"black","font-weight":"bold"});e.addEvent("click",function(){currentAffiliate=null;y.destroy()});h.appendText(" ");h.grab(e);y=n(h)}if(mobileAdWrapper){var z=new Element("div",{styles:{width:mobileAdWrapperSize.x+"px",height:mobileAdWrapperSize.y+"px"}});n(z);P=function(){mobileAdWrapper.setStyles({display:"block",position:"absolute"});mobileAdWrapper.setPosition(z.getPosition())};P();$(window).addEvent("resize",P)}if(IS_MOBILE)for(e=50;300>=
e;e+=50)setTimeout(l,e)}function ua(a){if("undefined"!==typeof Recaptcha){var b=new Element("form");b.setStyle("margin","0");b.setStyle("padding","0");b.addEvent("submit",function(a){a.preventDefault();i.submitRecaptcha(Recaptcha.get_challenge(),Recaptcha.get_response());q("Verifying...")});var c=new Element("div");c.setStyle("padding-left","1px");c.setStyle("padding-top","1px");b.grab(c);z(b);initialLogIsRecaptcha=!0;Recaptcha.create(a,c,{callback:function(){Recaptcha.focus_response_field();var a=
new Element("div");a.setStyle("padding-top","0.5em");var c=new Element("input");c.set("type","submit");c.set("value","Submit");a.grab(c);b.grab(a)},theme:"white"})}else{var d=new Element("iframe");d.setStyle("border","0 none");d.setStyle("padding",0);d.set("width",318);z(d);initialLogIsRecaptcha=!0;var f=d.contentWindow?d.contentWindow.document:d.contentDocument;d.addEvent("load",function(){var a=f.getElementById("theform");a&&(d.height=a.offsetHeight);(a=f.getElementById("recaptcha_response_field"))&&
a.focus()});f.open();f.write('<script type="application/javascript">var RecaptchaOptions = {theme: "white"};<\/script>');f.write('<style type="text/css">html, body, form { margin: 0; padding: 0; }</style>');f.write('<form id="theform">');f.write('<script type="text/javascript" src="http://www.google.com/recaptcha/api/challenge?k='+encodeURIComponent(a)+'"><\/script>');f.write('<div style="padding-top: 0.5em"><input type="submit" value="Submit"></div>');f.write("</form>");f.close();d.height=f.getElementById("theform").offsetHeight;
$(f.getElementById("theform")).addEvent("submit",function(a){a.preventDefault();var a=f.getElementById("recaptcha_challenge_field").value,b=f.getElementById("recaptcha_response_field").value;i.submitRecaptcha(a,b);setTimeout(function(){q("Verifying...")},0)})}}function W(){i.stopped||(i.disconnect(),n("You have disconnected."),x())}function za(){return"Leaving this page will end your conversation."}function pa(){switch(va){case "disconnect":K("really");!m.get("disabled")&&!IS_MOBILE&&m.focus();break;
case "really":W();break;case "new":E()}}function K(a,b){var c;switch(a){case "disconnect":c="Disconnect";break;case "really":c="Really?";break;case "new":c="New"}void 0!==b&&(c+=" ("+b+")");S.set("text",c);S.grab(new Element("div",{"class":"btnkbshortcut",text:"Esc"}));va=a}function ha(){null!==t&&(clearTimeout(t),t=null);IS_MOBILE||m.focus();var a=m.value;if(a){m.value="";if(IS_MOBILE){var b=m.clone();b.replaces(m);m=b}else m.focus();ia="";N("you",a);i.sendMessage(a);K("disconnect");for(b=0;b<T.length;b++){var c=
T[b];if((!IS_MOBILE||!c.noMobile)&&c.regex.test(a))if(null===currentAffiliate||currentAffiliate.priority<=c.priority)currentAffiliate=c}}}function Aa(){t=null;i.stopTyping()}$("appstore")&&$("appstore").destroy();$("footer")&&$("footer").destroy();mobileAdWrapper&&mobileAdWrapper.setStyle("display","none");var Z="string"===typeof a,ga=!1,qa=!1;$(document.body).addClass("inconversation");b&&$(document.body).addClass("videochat");var V=new Element("div",{"class":"chatbox3"}),s=new Element("div",{"class":"chatbox2"}),
ja=new Element("div",{"class":"chatbox"});IS_MOBILE&&V.grab(logoElt);var R=new Element("div",{"class":"logwrapper",styles:{top:contentTop+"px"}}),ka=new Element("div",{"class":"logbox"}),U=new Element("div");ka.grab(U);R.grab(ka);var aa=new Element("div",{"class":"logwrapperpush"});R.grab(aa);ja.grab(R);var Y=new Element("div",{"class":"controlwrapper"}),aa=new Element("table",{"class":"controltable",cellpadding:"0",cellspacing:"0",border:"0"}),wa=new Element("tbody"),ba=new Element("tr"),w=new Element("td",
{"class":"disconnectbtncell"}),u=new Element("div",{"class":"disconnectbtnwrapper"}),S=new Element("button",{"class":"disconnectbtn"});u.grab(S);w.grab(u);ba.grab(w);w=new Element("td",{"class":"chatmsgcell"});u=new Element("div",{"class":"chatmsgwrapper"});if(IS_MOBILE){var ca=new Element("form");ca.setStyles({margin:0,padding:0});ca.addEvent("submit",function(a){a.preventDefault();ha()});var m=new Element("input",{"class":"chatmsg disabled",disabled:!0,placeholder:"Type your message..."});ca.grab(m);
u.grab(ca)}else m=new Element("textarea",{"class":"chatmsg disabled",cols:"80",rows:"3",disabled:!0}),u.grab(m);w.grab(u);ba.grab(w);var w=new Element("td",{"class":"sendbthcell"}),u=new Element("div",{"class":"sendbtnwrapper"}),J=new Element("button",{"class":"sendbtn",disabled:!0,text:"Send"});J.grab(new Element("div",{"class":"btnkbshortcut",text:"Enter"}));u.grab(J);w.grab(u);IS_MOBILE||ba.grab(w);wa.grab(ba);aa.grab(wa);Y.grab(aa);ja.grab(Y);s.grab(ja);V.grab(s);$(document.body).grab(V);var P=
null;IS_MOBILE||($(document).addEvent("keydown",g),$(document).addEvent("keyup",j));var i=new MetaBackend;scrollElt=IS_MOBILE?document.body:ka;for(var O=[],fa=!1,T=[{regex:/horny|sexy|boob(?:ie)?s|\btits\b|nipples|penis|\bvag(?:\b|ina)|\bclit(?:oris)?|spank/i,url:"http://chaturbate.com/affiliates/in/hr8m/vmEwD/?track=default",text:"Looking for horny girls? You're in the wrong place. Go where the girls are! (18+)",style:{color:"blue","text-decoration":"underline"},noMobile:!0}],s=0;s<T.length;s++)T[s].priority||
(T[s].priotity=s);var H=[],D=null,ta=[];if($("logo")||logoElt)($("logo")||logoElt).addEvent("click",ra),($("logo")||logoElt).setStyle("cursor","pointer");var F=null,C=null,Q=null,L=null;i.addEvent("connectedToServer",function(){S.set("disabled",!1);window.onbeforeunload=za;$(window).addEvent("unload",W)});i.addEvent("failedToConnect",function(){q("Error connecting to server. Please try again.");x()});var A=null,I=null,xa=!1;i.addEvent("waiting",function(){serverManager.setKnownGood();if(Z)q("Looking for two strangers. Hang on.");
else{var a=new Element("div"),b=new Element("div",{text:"Looking for someone you can chat with. Hang on."});a.grab(b);if(ya){A=new Element("div",{"class":"commonlikescancel",text:"It may take a little while to find someone with common interests. If you get tired of waiting, you can "});var b=new Element("a",{href:"javascript:",text:"connect to a completely random stranger"}),c=function(){I&&(clearTimeout(I),I=null);A&&(i.stopLookingForCommonLikes(),A.destroy(),A=null)};b.addEvent("click",c);A.grab(b);
A.appendText(" instead.");a.grab(A);I=setTimeout(function(){xa=!0;c()},1E4)}q(a)}});i.addEvent("strangerConnected",function(a){serverManager.setKnownGood();b&&$("flash").gotStrangerPeerID(a);I&&(clearTimeout(I),I=null);Z?q("You're now watching two strangers discuss your question!","You're watching two strangers discuss your question on Omegle!"):(q("You're now chatting with a random stranger. Say hi!","You're chatting with a random stranger on Omegle!"),xa&&n("Omegle couldn't find anyone who shares interests with you, so this stranger is completely random. Try adding more interests!",
!1,!1,!1),m.set("disabled",!1),m.removeClass("disabled"),J.set("disabled",!1),IS_MOBILE||m.focus())});i.addEvent("gotMessage",function(a){ma();a=a.replace(/^[\r\n]+/g,"");navigator.notification&&navigator.notification.beep&&navigator.notification.beep(1);N("stranger",a)});i.addEvent("strangerDisconnected",function(){n("Your conversational partner has disconnected.");x()});i.addEvent("typing",function(){na("Stranger")});i.addEvent("stoppedTyping",ma);i.addEvent("recaptchaRequired",ua);i.addEvent("recaptchaRejected",
ua);i.addEvent("connectionDied",function(a){var b="Technical error";a&&(b+=": "+a+" Sorry. :( Omegle understands if you hate it now, but Omegle still loves you.");n(b);serverManager.unsetKnownGood();x()});i.addEvent("question",function(a){var b=new Element("div",{"class":"question"}),c=new Element("div",{"class":"questionHeading",text:"Question to discuss:"});b.grab(c);c=new Element("div",{"class":"questionText"});c.appendText(a);b.grab(c);O.push(["Question to discuss:",a]);r(b)});i.addEvent("spyMessage",
function(a,b){var c="Stranger 1"===a?"youmsg":"strangermsg";M(a);startFlashing();y(a,c,b)});i.addEvent("spyDisconnected",function(a){n(a+" has disconnected");x()});i.addEvent("spyTyping",na);i.addEvent("spyStoppedTyping",M);i.addEvent("error",function(a){n(a);x()});i.addEvent("antinudeBanned",function(a){n("Banned.");x();null!==L&&L();top.location.href=a});var la=null,G=null;i.addEvent("commonLikes",function(a){if(a.length){G=a;for(var a="You and the stranger both like ",b=0;b<G.length;b++)a+=G[b],
b<G.length-1&&(a+=", "),b==G.length-2&&(a+="and ");a+=".";la&&la.destroy();la=n(a)}});var va="disconnect";J.addEvent("click",ha);K("disconnect");S.addEvent("click",pa);var ia=m.value,t=null;m.addEvent("keydown",function(a){13==a.code&&(!a.shift&&!a.alt&&!a.meta)&&(ha(),a.preventDefault())});m.addEvent("keypress",function(){setTimeout(function(){m.value!==ia&&(ia=m.value,null===t&&i.typing(),null!==t&&(clearTimeout(t),t=null),t=setTimeout(Aa,5E3))},0)});q("Connecting to server...");var da=null,ya=
!1,ea=[],X=null;!c&&(!a&&shouldUseLikes)&&(shouldUseFbLikes&&(da=(s=FB.getAuthResponse())?s.accessToken:null),ea=topicManager.list(),ya=ea.length||null!==da);b?(flashCb_gotNearID=function(a){resetStratusCallbacks();i.connect(a,null,!1,!1,da,ea)},flashCb_errorConnectingToStratus=function(){resetStratusCallbacks();q("Error connecting to Adobe Stratus. Please try again.");x()},$("flash").startChat?$("flash").startChat():(x(),E(!1)),X=setTimeout(function(){X=null;var a=new Date;lastScreenshotTime&&6E4>
a-lastScreenshotTime||(lastScreenshotTime=a,Math.random()>screenshotPercent||$("flash").postScreenshot&&antinudeServers.length&&$("flash").postScreenshot(antinudeServers[$random(0,antinudeServers.length-1)]))},$random(1500,3E3))):i.connect(null,a,c,d,da,ea);serverManager.unsetKnownGood()};
